src/models/Question.php
<?
class Question extends ActiveRecord
{

	const	YEARFROM = 1962,
			YEARTO = 1991,
			STEP = 3;

	public
		$id,
		$name;

//	public $pull;

	public function tableName() {
		return 'questions';
	}
	public function relations() {
		return [
			'user' => [ self::BELONGS_TO, 'User', 'userId' ],
			'pulls' => [ self::HAS_MANY, 'Pull', 'questionId' ],
		];
	}

	public function attributeLabels() {
		return [
			'name' => 'Вопросы'
		];
	}

	public function rules() {
		return [
			['name', 'required'],
			['name', 'safe']
		];
	}

	public function defaultScope() {
		return [
			'alias' => 'q'
		];
	}
/*
	public function excludePulls($exclude) {
		$this->dbCriteria->addNotInCondition('pull.id',$exclude);
		return $this;
	}*/

	/*public function excludeYear($exclude) {
		$this->dbCriteria->addNotInCondition('q.yearFrom',$exclude);
		return $this;
	}*/

	public function search() {
		$criteria = new CDbCriteria;
		$criteria->order = 'yearFrom';

		return new CActiveDataProvider($this, [
			'criteria' => $criteria,
			'sort' => false,
			'pagination' => [
				'pageVar' => 'page',
				'pageSize' => 20
			],
		]);
	}

	/*public function getListAnswers() {
		if (empty($this->answers))
			return '<нет ответов на этот вопрос>';
		$res = [];
		foreach ($this->answers as $answer) {
			$res[] = CHtml::link($answer->id, app()->createAbsoluteUrl('questions/answer', [ 'id' => $answer->id ]));
		}
		return implode(', ', $res);
	}*/

	public function formatData() {
		$res = '<h4>'.$this->name.'</h4>';
		$res .= '<div class="pulls">'.$this->getBlocksPulls().'</div>';
		return $res;
	}

	public function getBlocksPulls() {
		if (empty($this->pulls))
			return '<нет пула ответов на этот вопрос>';
		$res = '';
		/** @var Pull $pull */
		foreach ($this->pulls as $pull) {
			$res .= CHtml::tag('div',['class'=>'pull','data-id'=>$pull->id], $pull->getListAnswers());
		}
		return $res;
	}

	public function getButtons() {
		return	(count($this->pulls)>=20 ? '' : (CHtml::link(CHtml::tag("span",['class'=>'glyphicon glyphicon-plus','aria-hidden'=>"true"],''), app()->createUrl('questions/pullAdd',['questionId'=>$this->id]), ['title'=>'Добавить ответы в этот вопрос']).' ')).
		CHtml::tag("span",['class'=>'question-delete glyphicon glyphicon-minus','aria-hidden'=>"true", 'data-id'=>$this->id, 'title'=>'Удалить вопрос с ответами'],'');
	}

	/**
	 * @return array
	 */
	public static function getRandomizeYearsFrom() {
		$array = self::getYearsFrom();
		shuffle($array);
		return $array;
	}

	/**
	 * @return array
	 */
	public static function getYearsFrom() {
		$array = [];
		for ($i = self::YEARFROM; $i <= self::YEARTO;$i+=self::STEP) {
			$array[$i] = $i.' - '.($i+self::STEP-1);
		}
		return $array;
	}

	public function getYearTo() {
		return $this->yearFrom + Question::STEP-1;
	}

	public function getRangeYears() {
		return $this->yearFrom . ' - ' . $this->yearTo;
	}

	/**
	 * Выбирает один пулл вопросов
	 * @return mixed
	 */
	public function getPull () {
		$idx = 0;
		$countPull = count($this->pulls);
		if ($countPull > 1) {
			$idx = rand(0,$countPull-1);
		}
		return $this->pulls[$idx];
	}

	/**
	 * Получение массива вопросов в формате <id> => <вопрос>
	 * @param bool $empty Массив вопросов с пустым полем
	 * @return array
	 */
	public static function getQuestionList($empty = false){
		$items = self::model()->findAll([
			'select' => '`id`,`name`'
		]);

		$list = CHtml::listData($items, 'id', 'name');

		if ($empty) {
			$list[0] = 'Нет вопроса';
			ksort($list);
		}
		return $list;
	}
}

src/controllers/QuestionsController.php
<?php

class QuestionsController extends Controller
{

	public function filters() {
		return array_merge(parent::filters(),[
			[
				'application.filters.AccessRootFilter'
			]
		]);
	}

	/**
	 * Список
	 */
	public function actionIndex($page = 1)
	{
		$model = new Question;
		$model->setAttribute('year',Question::YEARFROM);

		$this->render('index',[
			'model' => $model,
			'page' => $page
		]);
	}

	public function actionAdd()	{
		$model = new Question;
		if ($this->populate($_POST, $model)){
			if ($model->validate()) {
				$model->userId=app()->user->id;
				$model->dateAdd = new CDbExpression('NOW()');
				if (isset($_POST['yearFrom']))
					$model->yearFrom = Question::getYearsFrom()[$_POST['yearFrom']];
				$model->insert();
			}
		}
		$this->redirect(url('questions'));
	}

	public function actionPullAdd($questionId=null) {
		$model = new Pull;
		if ($this->populate($_POST, $model)) {
			if ($model->validate()) {

				$model->setAttribute('userId', app()->user->id);
				$model->setAttribute('dateAdd', new CDbExpression('NOW()'));
				if (!$model->save()) {
					throw new CException('Не могу сохранить запись');
				}
				$answer1 = new Answer;
				$answer2 = new Answer;
				$answer3 = new Answer;

				$answer1->name = $model->answer1;
				$answer2->name = $model->answer2;
				$answer3->name = $model->answer3;

				if ($model->wrong==1) $answer2->wrong = $answer3->wrong = 'N';
				if ($model->wrong==2) $answer1->wrong = $answer3->wrong = 'N';
				if ($model->wrong==3) $answer2->wrong = $answer1->wrong = 'N';

				$answer1->pullId = $answer2->pullId = $answer3->pullId = $model->id;
				$answer1->dateAdd = $answer2->dateAdd = $answer3->dateAdd = new CDbExpression('now()');


				$path = Yii::getPathOfAlias('assets.images.answers');
				if (!file_exists($path))
					@mkdir($path, 0755);

				if ($file1 = CUploadedFile::getInstance($model,'file1')) {
					$filename = $path . '/' . $file1->name;
					$file1->saveAs($filename);
					if ($file1->hasError) throw new CException('Не могу загрузить файл 1');
					$ext = CFileHelper::getExtension($filename);
					$answer1->setAttribute('image', $ext);
				}

				if ($answer1->save()) {
					if ($file1)
						if (!rename($path . '/' . $file1->name, $path . '/' . $answer1->id . '.' . $ext))
							throw new CException('Не могу создать правильный файл');
				} else {
					if ($file1) {
						@unlink($path . '/' . $file1->name);
						throw new CException('Не могу сохранить запись');
					}
				}

				if ($file2 = CUploadedFile::getInstance($model,'file2')) {
					$filename = $path . '/' . $file2->name;
					$file2->saveAs($filename);
					if ($file2->hasError) throw new CException('Не могу загрузить файл 2');
					$ext = CFileHelper::getExtension($filename);
					$answer2->setAttribute('image', $ext);
				}

				if ($answer2->save()) {
					if ($file2)
						if (!rename($path . '/' . $file2->name, $path . '/' . $answer2->id . '.' . $ext))
							throw new CException('Не могу создать правильный файл');
				} else {
					if ($file2) {
						@unlink($path . '/' . $file2->name);
						throw new CException('Не могу сохранить запись');
					}
				}

				if ($file3 = CUploadedFile::getInstance($model,'file3')) {
					$filename = $path . '/' . $file3->name;
					$file3->saveAs($filename);
					if ($file3->hasError) throw new CException('Не могу загрузить файл 3');
					$ext = CFileHelper::getExtension($filename);
					$answer3->setAttribute('image', $ext);
				}

				if ($answer3->save()) {
					if ($file3)
						if (!rename($path . '/' . $file3->name, $path . '/' . $answer3->id . '.' . $ext))
							throw new CException('Не могу создать правильный файл');
				} else {
					if ($file3) {
						@unlink($path . '/' . $file3->name);
						throw new CException('Не могу сохранить запись');
					}
				}


				$this->redirect(url('questions'));
			}
		}

		$this->render('pullAdd',[
			'model' => $model,
			'questionId' => $questionId
		]);
	}

	public function actionAnswerEdit($id) {
		if (!$id || !$model = Answer::model()->findByPk($id))
			throw new CHttpException(404, 'Нет такого ответа');

		if ($this->populate($_POST, $model)) {

			if ($model->validate()) {
				$path = Yii::getPathOfAlias('assets.images.answers');
				$ext = $model->image;

				if ($model->file = CUploadedFile::getInstance($model,'file')) {
					if (!file_exists($path))
						@mkdir($path, 0755);
					$filename = $path . '/' . $model->file->name;

					$model->file->saveAs($filename);

					if ($model->file->hasError)
						throw new CException('Не могу загрузить файл');
					$ext = CFileHelper::getExtension($path.'/'.$model->file->name);
					$model->setAttribute('image', $ext);
				}

				$model->setAttribute('userId', app()->user->id);
				$model->setAttribute('dateAdd', new CDbExpression('NOW()'));


				if ($model->save()) {
					if ($model->file)
						if (!rename($path.'/'.$model->file->name, $path.'/'.$model->id.'.'.$ext))
							throw new CException('Не могу создать правильный файл');

					$this->redirect(url('questions'));
				} else {
					if ($model->file) {
						@unlink($path . '/' . $model->file->name);
						throw new CException('Не могу сохранить запись');
					}
				}
			}
		}

		$this->render('answerAdd',[
			'model' => $model,
			'questionId' => $model->questionId
		]);

	}

	public function actionDelete($id) {
		if ($question = Question::model()->findByPk($id)) {

			foreach ($question->pulls as $pull) {
				foreach ($pull->answers as $answer) {
					if ($answer->image) {
						@unlink(Yii::getPathOfAlias('assets.images.answers') . '/' . $answer->id . '.' . $answer->image);
					}
					$answer->delete();
				}
				$pull->delete();
			}

			$question->delete();
		}

		$this->redirect(url('questions'));
	}


	public function actionQuestionDelete($id) {
		if ($question = Question::model()->findByPk($id)) {
			foreach ($question->answers as $answer) {
				if ($answer->image) {
					@unlink(Yii::getPathOfAlias('assets.images.answers') . '/' . $answer->id . '.' . $answer->image);
				}
				Answer::model()->deleteByPk($answer->id);
			}

			Question::model()->deleteByPk($id);
			$res['success'] = 'удалено успешно';
		} else {
			$res['error'] = 'Нет такого вопроса';
		}
		$this->renderJson($res);
	}

	public function actionAnswer($id) {
		if (!$id || !$model = Answer::model()->findByPk($id))
			throw new CHttpException(404,'Нет такого ответа');

		if ($this->populate($_POST, $model)) {

			if ($model->validate()) {
				$path = Yii::getPathOfAlias('assets.images.answers');
				$ext = $model->image;

				if ($model->file = CUploadedFile::getInstance($model,'file')) {
					if (!file_exists($path))
						@mkdir($path, 0755);
					$filename = $path . '/' . $model->file->name;

					$model->file->saveAs($filename);

					if ($model->file->hasError)
						throw new CException('Не могу загрузить файл');
					$ext = CFileHelper::getExtension($path.'/'.$model->file->name);
					$model->setAttribute('image', $ext);
				}

				$model->setAttribute('userId', app()->user->id);
				$model->setAttribute('dateAdd', new CDbExpression('NOW()'));


				if ($model->save()) {
					if ($model->file)
						if (!rename($path.'/'.$model->file->name, $path.'/'.$model->id.'.'.$ext))
							throw new CException('Не могу создать правильный файл');

					$this->redirect(url('questions'));
				} else {
					if ($model->file) {
						@unlink($path . '/' . $model->file->name);
						throw new CException('Не могу сохранить запись');
					}
				}
			}
		}

		$this->render('answer',[
			'answer' => $model
		]);
	}


}

src/views/questions/answer.php
<?
/**
 * @var $this QuestionsController
 * @var $answer Answer
 */
?>
<div class="container-fluid">
	<div class="well answer view">
		<h3 class="question"><?=$answer->pull->question->name?></h3>
		<?
			$form = $this->beginWidget('SActiveForm', [
				'action' => app()->createUrl('questions/answer/'.$answer->id),
				'method' => 'POST',
				'htmlOptions' => [ 'autocomplete' => "off",'enctype' => "multipart/form-data" ]
			]);
		?>
		<div class="form-group<?= $answer->hasErrors('name') ? ' has-error' : '' ?>">
			<?= CHtml::activeTextArea($answer, 'name', [ 'class' => 'form-control', 'rows'=>3, "placeholder" => "Введите ответ" ]) ?>
			<?= $form->error($answer,'name'); ?>
		</div>

		<div class="image"><?=$answer->img?></div>

		<div class="form-group<?= $answer->hasErrors('file') ? ' has-error' : '' ?>">
			<label class="control-label" for="file">Картинка</label>
			<?= $form->fileField($answer, 'file', [ 'class' => 'form-control' ]) ?>
			<?= $form->error($answer,'file'); ?>
		</div>
		<?=CHtml::activeHiddenField($answer, 'id', [ 'value' => $answer->id ])?>
		<button type="submit" class="btn btn-default">Сохранить</button>

		<?$this->endWidget();?>
	</div>
</div>

src/views/questions/index.php
<div class="container-fluid">
	<div class="filter well">
		<?
			$this->pageTitle = 'Список вопросов';
			$form = $this->beginWidget('SActiveForm', [
				'action' => app()->createUrl('questions/add'),
				'method' => 'POST',
				'htmlOptions' => [ 'autocomplete' => "off" ]
			]);
		?>
			<div class="form-group<?= $model->hasErrors('name') ? ' has-error' : '' ?>">
				<label for="quest">Новый вопрос</label>
				<?= CHtml::activeTextArea($model, 'name', [ 'class' => 'form-control', 'rows'=>3, "placeholder" => "Введите вопрос" ]) ?>
				<?= $form->error($model,'name'); ?>
			</div>
			<div class="form-group<?= $model->hasErrors('year') ? ' has-error' : '' ?>">
				<label for="quest">Начальный год</label><br>
				<?= CHtml::dropDownList('yearFrom', Question::YEARFROM, Question::getYearsFrom()); ?>
				<?= $form->error($model,'year'); ?>
			</div>
			<button type="submit" class="btn btn-default">Добавить</button>
		<?$this->endWidget();?>
	</div>
</div>


<?
	$this->widget('zii.widgets.grid.CGridView', [
		'id' => get_class($this).'-grid',
		'ajaxUpdate' => false,
		'dataProvider' => $model->search(),
		'columns' => [
			[
				'header' => 'Год',
				'type' => 'raw',
				'value' => '$data->rangeYears',
			],
			[
				'type' => 'raw',
				'value' => '$data->formatData()',
			],

			[
				'header' => '',
				'type' => 'raw',
				'value' => '$data->buttons',
			]
		],
	]);

src/views/questions/pullAdd.php
<?
	/**
	 * @var $this QuestionsController
	 * @var $model Answer
	 */
?>
<div class="container-fluid">
	<div class="well answers add">
		<?
			$this->pageTitle = ($model->id ? 'Редактировать':'Добавить').' ответ';
			$form = $this->beginWidget('SActiveForm', [
				'action' => app()->createUrl('questions/'. ($model->id ? 'pullEdit/'.$model->id:'pullAdd')),
				'method' => 'POST',
				'htmlOptions' => [ 'autocomplete' => "off",'enctype' => "multipart/form-data" ]
			]);
		?>
		<div class="form-group<?= $model->hasErrors('questionId') ? ' has-error' : '' ?>">
			<label for="quest">Ответ на вопрос: </label>
			<?= CHtml::activeDropDownList($model, 'questionId', Question::getQuestionList(true), ['options'=>[$questionId => ['selected'=>true]]]); ?>
			<?= $form->error($model,'questionId'); ?>
		</div>

			<?
				for ($i=1; $i<=3; $i++) {?>

					<div class="answer">
						<div class="form-group<?= $model->hasErrors('answer'.$i) ? ' has-error' : '' ?>">
							<?= CHtml::activeTextArea($model, 'answer'.$i, [ 'class' => 'form-control', 'rows'=>3, "placeholder" => "Введите ответ" ]) ?>
							<?= $form->error($model,'answer'.$i); ?>
							<div class="radio">
								<label>
									<input value="<?=$i?>" type="radio" name="Pull[wrong]"> Неправильный ответ
								</label>
							</div>
						</div>

						<? if ($model->id){?>
							<div class="image"><?=$model->img?></div>
						<?}?>
						<div class="form-group<?= $model->hasErrors('file'.$i) ? ' has-error' : '' ?>">
							<label class="control-label" for="Pull_file2">Картинка <?=$i?></label>
							<?= $form->fileField($model, 'file'.$i, [ 'class' => 'form-control' ]) ?>
							<?= $form->error($model,'file'.$i); ?>
						</div>

					</div>

			<?}?>
			<? if ($model->id){
				echo CHtml::activeHiddenField($model, 'id', [ 'value' => $model->id ]);
			}?>

		<button type="submit" class="btn btn-default"><?=$model->id ? 'Сохранить':'Добавить'?></button>
		<?$this->endWidget();?>
	</div>
</div>